### ISSUE TITLE
Midi Crash error Keyboard value:

### ISSUE THREAD

**Issue by MayiVT** [Stereo101/python-MidiToVirtualPianoMacro#23]
Exception in thread Thread-94:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/Users/mayivt/Downloads/python-MidiToVirtualPianoMacro-master/Source/playSong.py", line 137, in playNextNote
    pressLetter(n)
  File "/Users/mayivt/Downloads/python-MidiToVirtualPianoMacro-master/Source/playSong.py", line 40, in pressLetter
    keyboard.press('left shift')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/keyboard/__init__.py", line 396, in press
    send(hotkey, True, False)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/keyboard/__init__.py", line 379, in send
    parsed = parse_hotkey(hotkey)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/keyboard/__init__.py", line 358, in parse_hotkey
    steps.append(tuple(key_to_scan_codes(key) for key in keys))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/keyboard/__init__.py", line 358, in <genexpr>
    steps.append(tuple(key_to_scan_codes(key) for key in keys))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/keyboard/__init__.py", line 324, in key_to_scan_codes
    raise ValueError('Key {} is not mapped to any known key.'.format(repr(key)), e)
ValueError: ("Key 'left shift' is not mapped to any known key.", ValueError('Unrecognized character: left shift'))

**Comment by Stereo101** [comment]
This is from running "python playSong.py" right? Not the "playSong.exe" file? 

It looks like you're using python 3.9 while the last time I worked on this I was using python 3.8.6. This shouldn't matter at all, but there might have been a slight change to the underlying keyboard library. My first guess would be changing the code in playSong.py : lines 39 42 from "left shift" to just "shift"

[although, it looks like both "left shift" and "shift" are still supported](https://github.com/boppreh/keyboard#keyboardall_modifiers)

**Comment by Stereo101** [comment]
I guess the keycodes can also be language sensitive depending on what language you have installed on your OS, [which may or may not have been fixed already](https://github.com/boppreh/keyboard/issues/12). If you don't have English as your OS locale open up a python REPL and type:

`import keyboard`
`keyboard.all_modifiers`

The correct wording you need for the "shift" modifier should be there. You would probably need to make changes to lines 175-177 as well.

**Comment by Stereo101** [comment]
I changed playSong to use keycodes instead of the key names, so it should work on all locales now. Download it again and see if it is working for you now.

**Comment by Stereo101** [comment]
Can anyone with a non-english windows installation confirm this?
